"""Add_AnalyticsLog

Revision ID: 33d1e67579f6
Revises: 5491e39755d8
Create Date: 2026-08-12 14:07:15.179463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '33d1e67579f6'
down_revision: Union[str, Sequence[str], None] = '5491e39755d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('generation_attempted', sa.Boolean(), nullable=True),
    sa.Column('generated_game_id', sa.String(), nullable=True),
    sa.Column('clarification_needed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_logs_id'), 'analytics_logs', ['id'], unique=False)
    op.create_index(op.f('ix_analytics_logs_user_id'), 'analytics_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analytics_logs_user_id'), table_name='analytics_logs')
    op.drop_index(op.f('ix_analytics_logs_id'), table_name='analytics_logs')
    op.drop_table('analytics_logs')
    # ### end Alembic commands ###
