"""Add_UserLike_model

Revision ID: 5491e39755d8
Revises: 9bef410f4e07
Create Date: 2026-08-12 12:48:28.477568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '5491e39755d8'
down_revision: Union[str, Sequence[str], None] = '9bef410f4e07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_likes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_likes_game_id'), 'user_likes', ['game_id'], unique=False)
    op.create_index(op.f('ix_user_likes_id'), 'user_likes', ['id'], unique=False)
    op.create_index(op.f('ix_user_likes_user_id'), 'user_likes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_likes_user_id'), table_name='user_likes')
    op.drop_index(op.f('ix_user_likes_id'), table_name='user_likes')
    op.drop_index(op.f('ix_user_likes_game_id'), table_name='user_likes')
    op.drop_table('user_likes')
    # ### end Alembic commands ###
